# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yandex511.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import Busket
from modelPath import model


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 640)
        MainWindow.setMinimumSize(QtCore.QSize(480, 640))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 30, 55, 16))
        self.label.setObjectName("label")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(80, 540, 381, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(30, 70, 421, 401))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 419, 399))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")

        self.BusketProducts()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Корзина"))
        self.pushButton_6.setText(_translate("MainWindow", "Категории"))
        self.pushButton_5.setText(_translate("MainWindow", "оплата"))

    def BusketProducts(self):
        self.ram = open("RamCash/currentUser", "rb")
        self.BusProducts = model.BusketProductsGet(int(self.ram.read()))
        self.ProductsId = model
        for i in self.BusProducts:

            self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
            self.groupBox.setMinimumSize(QtCore.QSize(381, 181))
            self.groupBox.setMaximumSize(QtCore.QSize(397, 181))
            self.groupBox.setObjectName("groupBox")
            self.label_6 = QtWidgets.QLabel(self.groupBox)
            self.label_6.setGeometry(QtCore.QRect(20, 30, 131, 131))
            self.label_6.setText("")
            self.label_6.setPixmap(QtGui.QPixmap("2022-11-10_21-47-51.png"))
            self.label_6.setScaledContents(True)
            self.label_6.setObjectName("label_6")
            self.label_5 = QtWidgets.QLabel(self.groupBox)
            self.label_5.setGeometry(QtCore.QRect(180, 40, 55, 16))
            self.label_5.setObjectName("label_5")
            self.label_7 = QtWidgets.QLabel(self.groupBox)
            self.label_7.setGeometry(QtCore.QRect(180, 70, 55, 16))
            self.label_7.setObjectName("label_7")
            self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
            self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(160, 110, 221, 41))
            self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
            self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
            self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
            self.horizontalLayout_3.setObjectName("horizontalLayout_3")
            self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
            self.pushButton_3.setObjectName("pushButton_3")
            self.horizontalLayout_3.addWidget(self.pushButton_3)
            self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
            self.lineEdit_4.setObjectName("lineEdit_4")
            self.horizontalLayout_3.addWidget(self.lineEdit_4)
            self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
            self.pushButton_4.setObjectName("pushButton_4")
            self.horizontalLayout_3.addWidget(self.pushButton_4)
            self.pushButton = QtWidgets.QPushButton(self.groupBox)
            self.pushButton.setGeometry(QtCore.QRect(260, 40, 93, 28))
            self.pushButton.setObjectName("pushButton")
            self.verticalLayout.addWidget(self.groupBox)
            self.scrollArea.setWidget(self.scrollAreaWidgetContents)
            self.label_5.setText("название")
            self.label_7.setText("цена")
            self.pushButton_3.setText("-")
            self.pushButton_4.setText("+")
            self.pushButton.setText("удалить")
        self.ram.close()